#!/usr/bin/bash

# A utility to remember bash colors.
# Based on: https://stackoverflow.com/a/33206814

E="\e[1m\e[33m" # Emphasize
R="\e[0m"       # Reset

print_colors() {
    echo -e "\\\033[$E<N>${R}m                - Use color with code N"
    echo -e "\\\033[$E<R>;<G>;<B>${R};194;0m  - Use RGB color"
    echo -e "\\\033[0m                  - Reset color"

    for i in {30..38}; do
        printf "\033[${i}m$i\033[0m  "
    done
    echo "";
    for i in {90..98}; do
        printf "\033[${i}m$i\033[0m  "
    done
    echo "";
}

print_commands() {
    echo -e "\\\033[2K         - Clear Line"
    echo -e "\\\033[$E<L>;<C>${R}H   - Put cursor at line L and col C."
    echo -e "\\\033[$E<L>;<C>${R}f   - (same as above)"
    echo -e "\\\033[$E<N>${R}A       - Move cursor up N lines"
    echo -e "\\\033[$E<N>${R}B       - Move cursor down N lines"
    echo -e "\\\033[$E<N>${R}C       - Move cursor forward N columns"
    echo -e "\\\033[$E<N>${R}D       - Move cursor backward N columns"
    echo -e "\\\033[2J         - Clear screen, move to (0,0)"
    echo -e "\\\033[K          - Erase to end of line"
    echo -e "\\\033[s          - Save cursor position"
    echo -e "\\\033[u          - Restore cursor position"
    echo -e "\\\033[4m         - Underline on"
    echo -e "\\\033[24m        - Underline off"
    echo -e "\\\033[1m         - Bold on"
    echo -e "\\\033[21m        - Bold off"
}

## Only print ANSII color escape codes.
if [[ "$1" == "preview" ]]; then

    print_colors
## Print all ANSII format escape codes.
elif [[ "$1" == "full" ]]; then

    print_colors
    echo "";
    print_commands

else
    echo "A utility to remember ANSII colors codes."
    ~/.scripts/script_help $0
fi
